name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      - name: Deploy Application
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          DEPLOY_PATH: "/home/ubuntu/fastapi-app"
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@$SERVER_IP << 'EOF'
            cd $DEPLOY_PATH
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            systemctl restart fastapi-app || sudo systemctl restart fastapi-app
          EOF
