name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      - name: Deploy Application
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          DEPLOY_PATH: "/home/ubuntu/fastapi-app"
          GIT_REPO: "git@github.com:your-username/your-repo.git"  # Replace with your actual repo
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@$SERVER_IP << EOF
            set -e  # Stop execution if any command fails

            DEPLOY_PATH="${DEPLOY_PATH}"
            GIT_REPO="${GIT_REPO}"  # Explicitly define GIT_REPO inside SSH

            echo "Using DEPLOY_PATH: \$DEPLOY_PATH"
            echo "Using GIT_REPO: \$GIT_REPO"

            # Ensure the deployment directory exists
            if [ ! -d "\$DEPLOY_PATH" ]; then
              echo "DEPLOY_PATH (\$DEPLOY_PATH) does not exist! Creating it..."
              mkdir -p "\$DEPLOY_PATH"
            fi

            cd \$DEPLOY_PATH

            # Ensure it's a git repository, if not clone it
            if [ ! -d ".git" ]; then
              echo "No Git repository found! Cloning from \$GIT_REPO..."
              git clone "\$GIT_REPO" .  # Corrected repository path
            fi

            git reset --hard  # Ensure a clean state
            git pull origin main

            # Ensure Python and dependencies are installed
            if ! command -v python3 &> /dev/null; then
              echo "Python3 is not installed. Installing..."
              sudo apt update && sudo apt install -y python3 python3-venv python3-pip
            fi

            # Ensure virtual environment exists
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi

            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

            # Restart the service
            sudo systemctl restart fastapi-app || sudo systemctl restart fastapi-app.service
          EOF
